### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mukulsaini-dev**
This is the initial version of my component library.

### CODE REVIEW

**Review by SauravKumar-max — COMMENTED** [review]
In the Docs anchor tag the link should be of the avatar component page instead of the alert because your docs page starts with the avatar component first

**Comment by AnkitKarnAK** [comment]
Hey @mukulsaini-dev,

Some of the links are broken.
On Alert Component page: Docs link on navbar doesn't exist
On Getting Started or any component page (except Alert): Home link on navbar doesn't exist
On Card component page: Getting started link on sidebar is wrong.

**Comment by shivamupadhyay008** [comment]
hey @mukulsaini-dev 
1: landing page name  of UI is crush and in getting started page that ghost UI change it to make the same
2:in home page docs link is break
3: in the sidebar change the decrease font size of the footer "made with love" so it looks in a line 
4: in the check box, radio button and button use pointer cursor  when hovering now its just pointer

**Comment by mukulsaini-dev** [comment]
> 
> 
> In the Docs anchor tag the link should be of the avatar component page instead of the alert because your docs page starts with the avatar component first

thanks for the feedback @SauravKumar-max  I changed the alert component link to avatar component link in Docs page.
#2

**Comment by mukulsaini-dev** [comment]
Hey @AnkitKarnAK Thanks for the feedback , i refactored my code and fix the links of all components.
#5

**Comment by mukulsaini-dev** [comment]
> 
> 
> hey @mukulsaini-dev
> 1: landing page name of UI is crush and in getting started page that ghost UI change it to make the same
> 2:in home page docs link is break
> 3: in the sidebar change the decrease font size of the footer "made with love" so it looks in a line
> 4: in the check box, radio button and button use pointer cursor when hovering now its just pointer

Hey @shivamupadhyay008  , 
Thanks for the feedback , i fixed the link in docs , logo name and add hover effects on buttons 
#6

**Pull request merged**
